### ISSUE TITLE
I can't make 1.75mm filament

### ISSUE THREAD

**Issue by santisantisanti** [filipmu/Marlin-Mackerel#11]
Hi,

In the actual firmware the desired diameter goes from 1.70 to 1.80 directly. Anyone knows what do I need to change for being able to set 1.75mm diameter?

Thank you!

**Comment by filipmu** [comment]
There is a new Release Candidate that allows more fine grained control, as well as some new features. [https://github.com/filipmu/Marlin-Mackerel/tree/Release-Candidate].  Give that a try.
