### ISSUE TITLE
Extruder speed

### ISSUE THREAD

**Issue by CFTechno** [filipmu/Marlin-Mackerel#3]
Might it be an idea to have an option to set extruder speed before first having to select "resume extruder" and then "Tune" ? Specially when directly at start the extruder will stall. When a stall happens I rather first select "pause extruder" and then change the speed then letting the stall continue and select "tune" and changing the extruder speed.

**Comment by filipmu** [comment]
There is a 'Prepare' menu item that allows you to set up everything, and then go to warmup before resuming the extruder.
