### ISSUE TITLE
How can I change extruder stepper motor with a DC motor?

### ISSUE THREAD

**Issue by tanahy** [filipmu/Marlin-Mackerel#8]
Hi,

I'm trying to swap the extruder stepper motor with a DC motor, as I got a geared one that should work well enough. My idea is to swap the winder motor with the stepper using the firmware, but I don't know which parts of the firmware I should change.

I have checked in the code and it seems I only need to change some stuff between the lines 722-877 on the Mackerel.h file. Is there anything else that I need to be aware of?

**Comment by filipmu** [comment]
This code is really all about controlling stepper motors.  I would not know where to begin changing that code to pulse width control a DC motor.  I would recommend looking at this project to see the beginnings of a version for brushed DC motors.

http://www.thingiverse.com/thing:1454222
